name: Check Build

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches: [master, next]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install npm 7
        run: npm i -g npm@7

      # Installs the dependencies
      - name: Install Dependencies
        run: npm ci

      # Runs lints
      - name: Run Linter
        run: npm run code-sanity

      # Build
      - name: Build
        run: npm run build:packages

      # Runs tests
      - name: Runs tests
        run: npm run test:ci
