name: Delete gh-pages folder of a closed PR

on:
  pull_request:
    branches:
      - test-gh-preview-deploy
    types: [closed]
env:
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  remove:
    runs-on: ubuntu-latest
    continue-on-error: true
    # if: github.event.pull_request.merged == true
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      # Git Config
      - name: Set Git Config
        run: git config --global user.email "runway-frontend-coe@freshworks.com" && git config --global user.name "runway-frontend-coe"

      - name: Remove File
        run: |
            rm -- -rf ./${{env.PR_NUMBER}} \
            git add . \
            HUSKY_SKIP_HOOKS=1 git commit -m "Delete directory that is not required" --no-verify \
            HUSKY_SKIP_HOOKS=1 git push origin gh-pages --no-verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
