name: Release

on:
  push:
    branches: [test-publish]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install npm 7
        run: npm i -g npm@7

      # Installs the dependencies
      - name: Install Dependencies
        run: npm ci

      # Runs lints
      - name: Run Linter
        run: npm run code-sanity

      # Build
      - name: Build
        run: npm run build

      # Runs tests
      #- name: Runs tests
      #  run: npm run test

      # SetGit Identity
      - name: Set Git Identity
        run: |
          git config --global user.name 'runway-frontend-coe'
          git config --global user.email 'runway-frontend-coe@freshworks.com'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Creates git tags
      - name: Create Git Tags
        run: npm run update-version:ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Publish to NPM
      - name: NPM Publish
        run: npm run release:ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
