name: Deploy preview

on:
  pull_request:
    branches: [test-gh-preview-deploy]

permissions:
  contents: read
  pages: write
  id-token: write
  
env:
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  deploy:
    runs-on: [self-hosted, Linux]
    continue-on-error: true
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install npm 7
        run: npm i -g npm@7

      # Installs the dependencies
      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VUEPRESS_BASE: ${{ format('{0}{1}/', '/gh-preview-deploy/', env.PR_NUMBER) }}

       - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: 'www-dist'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
 

      # - name: Deploy
      #   uses: JamesIves/github-pages-deploy-action@4.1.1
      #   with:
      #     branch: master
      #     folder: www-dist
      #     target-folder: ${{ env.PR_NUMBER }}

      - name: Publish env
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Preview environment
          message: |
            ## Preview environment
            https://kulkarni-kashyap.github.io/gh-preview-deploy/${{ env.PR_NUMBER }}/
