name: Deploy preview

on:
  pull_request:
    branches: [test-gh-preview-deploy]

permissions:
  contents: read
  pages: write
  id-token: write
  actions: write
  
env:
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    continue-on-error: true
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install npm 7
        run: npm i -g npm@7

      # Installs the dependencies
      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VUEPRESS_BASE: ${{ format('{0}{1}/', '/crayons/', env.PR_NUMBER) }}
          
          
      - name: Deploy
        uses: freshactions/github-pages-deploy-action@v4
        with:
          folder: www-dist
          target-folder: ${{ env.PR_NUMBER }}
